export const JOB_CATEGORIES = [
  'All Categories',
  'Software Development',
  'Web Development',
  'Mobile Development',
  'Frontend Development',
  'Backend Development',
  'Full Stack Development',
  'Data Science',
  'Data Analysis',
  'Data Engineering',
  'Machine Learning',
  'Artificial Intelligence',
  'Design',
  'UI/UX Design',
  'Graphic Design',
  'Product Design',
  'Product Management',
  'Project Management',
  'DevOps',
  'Cloud Engineering',
  'System Administration',
  'Marketing',
  'Digital Marketing',
  'Content Marketing',
  'Social Media Marketing',
  'Sales',
  'Business Development',
  'Customer Success',
  'Human Resources',
  'Recruiting',
  'Finance',
  'Accounting',
  'Operations',
  'Quality Assurance',
  'Testing',
  'Security',
  'Cybersecurity',
  'Network Engineering',
  'Database Administration',
  'Business Analysis',
  'Consulting',
  'Customer Support',
  'Technical Writing',
  'Research',
  'Education',
  'Training',
  'Legal',
  'Healthcare',
  'Real Estate',
  'Retail',
  'Manufacturing',
  'Logistics',
  'Supply Chain',
  'Other'
];

export const JOB_LOCATIONS = [
  'All Locations',
  'Remote',
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe'
];

export const AGENT_CONFIG_NUMBER_FIELDS = [
  {
    key: "thresholdPercent",
    label: "Match Threshold (%)",
    helper: "Score required before automated actions can run",
    min: 0,
    max: 100,
    step: 1,
  },
  {
    key: "bidBudgetMin",
    label: "Minimum Bid Budget ($)",
    helper: "Lowest amount the agent can bid",
    min: 0,
    step: 1,
  },
  {
    key: "bidBudgetMax",
    label: "Maximum Bid Budget ($)",
    helper: "Highest allowed bid",
    min: 0,
    step: 1,
  },
  {
    key: "bidStep",
    label: "Bid Increment ($)",
    helper: "Increment used when increasing bids",
    min: 1,
    step: 1,
  },
  {
    key: "maxCandidatesToBid",
    label: "Max Candidates to Bid",
    helper: "Concurrent candidates the agent can engage",
    min: 1,
    step: 1,
  },
  {
    key: "maxDailySpending",
    label: "Daily Spending Limit ($)",
    helper: "Maximum daily agent spending",
    min: 0,
    step: 1,
  },
  {
    key: "agentLifetimeDays",
    label: "Agent Lifetime (days)",
    helper: "Auto-deactivation period",
    min: 1,
    step: 1,
  },
  {
    key: "bidLifetimeDays",
    label: "Bid Lifetime (days)",
    helper: "How long a bid remains valid",
    min: 1,
    step: 1,
  },
]
