const TECHNICAL_ASSESSMENT_QUESTIONS_COUNT = 7;
const BUSINESS_ASSESSMENT_QUESTIONS_COUNT = 7;

const Team = 5;
const EXPIRATION_HOURS = 24;

const PROJECT_ASSESSMENT_TYPE = Object.freeze({
  TECHNICAL: "technical",
  BUSINESS: "business",
});

const PROJECT_STATUS = Object.freeze({
  PENDING: "pending",
  IN_PROGRESS: "inProgress",
  DONE: "done",
});

const PITCH_DURATION = 3; // in minutes
const QUESTION_DURATION = 2; // in minutes

const BUSINESS_QUESTION_DURATION = 2; // in minutes
const BUSINESS_PITCH_DURATION = 3; // in minutes

const TECH_STACK_TYPES = Object.freeze({
  HEDERA_TOOLING: "hederaTooling",
  HEDERA_SERVICE: "hederaService",
  CORE_TECH: "coreTech",
  INTEGRATION_TOOL: "integrationTool",
  INFRASTRUCTURE: "infrastructure",
});

const TECH_TYPE_WEIGHTS = {
  HEDERA_TOOLING: 0.2,
  HEDERA_SERVICE: 0.3,
  CORE_TECH: 0.25,
  INTEGRATION_TOOL: 0.15,
  INFRASTRUCTURE: 0.1,
};

const BUSINESS_OVERALL_SCORE_WEIGHTS = {
  INNOVATION: 0.3,
  BUSINESS_MODEL: 0.2,
  MARKET_POTENTIAL: 0.2,
  HEDERA_ECOSYSTEM_IMPACT: 0.2,
  TRACK_ALIGNMENT: 0.1,
};

const TECHNICAL_OVERALL_SCORE_WEIGHTS = {
  TECH_STACK: 0.5,
  ARCHITECTURE: 0.3,
  SCALABILITY_APPROACH: 0.2,
};



const ASSESSMENT_OVERALL_SCORE_WEIGHTS = {
  TECHNICAL: 0.3,
  BUSINESS: 0.3,
  CODE: 0.4
};

const ELIGIBILITY_REQUIREMENTS = Object.freeze({
  TRACK_MATCH: "track_match",
  CODE_SUBMISSION_ON_TIME: "code_submission_on_time",
});

const ELIGIBILITY_CHECKS_STATUS = Object.freeze({
  IS_NOT_CHECKED: "isNotChecked",
  IS_APPROVED: "isApproved",
  IS_NOT_APPROVED: "isNotApproved",
});

const MIN_TRACK_ALIGNMENT_SCORE = 20; 

module.exports = {
  TECHNICAL_ASSESSMENT_QUESTIONS_COUNT,
  BUSINESS_ASSESSMENT_QUESTIONS_COUNT,
  PROJECT_ASSESSMENT_TYPE,
  TECH_STACK_TYPES,
  PITCH_DURATION,
  BUSINESS_PITCH_DURATION,
  QUESTION_DURATION,
  BUSINESS_QUESTION_DURATION,
  PROJECT_STATUS,
  BUSINESS_OVERALL_SCORE_WEIGHTS,
  TECHNICAL_OVERALL_SCORE_WEIGHTS,
  TECH_TYPE_WEIGHTS,
  ASSESSMENT_OVERALL_SCORE_WEIGHTS,
  ELIGIBILITY_REQUIREMENTS,
  ELIGIBILITY_CHECKS_STATUS,
  MIN_TRACK_ALIGNMENT_SCORE,
  Team
};
