const TECHNICAL_ASSESSMENT_QUESTIONS_COUNT = 5;
const BUSINESS_ASSESSMENT_QUESTIONS_COUNT = 5;

const PROJECT_ASSESSMENT_TYPE = Object.freeze({
  TECHNICAL: "technical",
  BUSINESS: "business",
});

const PITCH_DURATION = 5; // in minutes
const QUESTION_DURATION = 4; // in minutes

module.exports = {
  TECHNICAL_ASSESSMENT_QUESTIONS_COUNT,
  BUSINESS_ASSESSMENT_QUESTIONS_COUNT,
  PROJECT_ASSESSMENT_TYPE,
  PITCH_DURATION,
  QUESTION_DURATION,
};
