const TECHNICAL_ASSESSMENT_QUESTIONS_COUNT = 5;
const BUSINESS_ASSESSMENT_QUESTIONS_COUNT = 6;

const PROJECT_ASSESSMENT_TYPE = Object.freeze({
  TECHNICAL: "technical",
  BUSINESS: "business",
});

const PROJECT_STATUS = Object.freeze({
  PENDING: "pending",
  IN_PROGRESS: "inProgress",
  DONE: "done",
});

const PITCH_DURATION = 5; // in minutes
const QUESTION_DURATION = 4; // in minutes

const BUSINESS_QUESTION_DURATION = 2; // in minutes
const BUSINESS_PITCH_DURATION = 3; // in minutes

const BUSINESS_OVERALL_SCORE_WEIGHTS = {
  INNOVATION: 0.3,
  BUSINESS_MODEL: 0.4,
  MARKET_POTENTIAL: 0.3,
};


module.exports = {
  TECHNICAL_ASSESSMENT_QUESTIONS_COUNT,
  BUSINESS_ASSESSMENT_QUESTIONS_COUNT,
  PROJECT_ASSESSMENT_TYPE,
  PITCH_DURATION,
  BUSINESS_PITCH_DURATION,
  QUESTION_DURATION,
  BUSINESS_QUESTION_DURATION,
  PROJECT_STATUS,
  BUSINESS_OVERALL_SCORE_WEIGHTS,
};
