export const companyChatSx = {
  workspace: {
    display: "flex",
    flexDirection: "column",
    gap: 1.5,
    height: "calc(100vh - 100px)",
    minHeight: 0,
  },
  hubHeader: {
    borderRadius: "18px",
    border: "1px solid #E8EAED",
    bgcolor: "#fff",
    px: { xs: 1.5, sm: 2.5 },
    py: { xs: 1.5, sm: 2 },
    display: "flex",
    alignItems: { xs: "stretch", md: "center" },
    justifyContent: "space-between",
    gap: 2,
    flexWrap: "wrap",
    boxShadow: "0 8px 24px rgba(15, 23, 42, 0.04)",
  },
  hubIntro: {
    flex: "1 1 220px",
    minWidth: 0,
  },
  hubEyebrow: {
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "#9CA3AF",
    mb: 0.5,
  },
  hubTitle: {
    fontSize: { xs: "1.1rem", sm: "1.25rem" },
    fontWeight: 700,
    color: "#111827",
    lineHeight: 1.2,
  },
  hubSubtitle: {
    fontSize: "13px",
    color: "#6B7280",
    mt: 0.5,
    maxWidth: 560,
  },
  hubNavWrap: {
    flex: { xs: "1 1 100%", md: "0 1 auto" },
    display: "flex",
    justifyContent: { xs: "stretch", md: "flex-end" },
  },
  content: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 1.5,
    px: 2,
    py: 1.25,
    borderBottom: "1px solid #F3F4F6",
    bgcolor: "#FCFCFD",
    flexWrap: "wrap",
  },
} as const;
