export const chatSegmentedControlSx = {
  root: {
    display: "flex",
    alignItems: "center",
    gap: 0.75,
    p: 0.5,
    bgcolor: "#F9FAFB",
    borderRadius: "12px",
    border: "1px solid #EEF0F2",
    flexWrap: "wrap",
    justifyContent: { xs: "stretch", sm: "flex-start" },
  },
  item: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 0.75,
    px: { xs: 1.25, sm: 1.75 },
    py: 0.875,
    borderRadius: "10px",
    textDecoration: "none",
    color: "#6B7280",
    border: "1px solid transparent",
    transition: "background-color 0.15s ease, border-color 0.15s ease, color 0.15s ease, box-shadow 0.15s ease",
    flex: { xs: 1, sm: "0 0 auto" },
    minWidth: 0,
    cursor: "pointer",
    bgcolor: "transparent",
    "&:hover": {
      bgcolor: "#fff",
      color: "#374151",
    },
  },
  itemActive: {
    bgcolor: "#fff",
    borderColor: "#99F6E4",
    color: "#0F766E",
    boxShadow: "0 1px 3px rgba(15, 118, 110, 0.12)",
  },
  icon: {
    fontSize: 18,
    color: "inherit",
  },
  label: {
    fontSize: "13px",
    fontWeight: 600,
    lineHeight: 1.2,
    whiteSpace: "nowrap",
  },
  badge: {
    minWidth: 18,
    height: 18,
    px: 0.5,
    borderRadius: "999px",
    bgcolor: "#0F766E",
    color: "#fff",
    fontSize: "10px",
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
} as const;
