export const companyChatSx = {
  workspace: {
    display: "flex",
    flexDirection: "column",
    gap: 1.5,
    flex: 1,
    minHeight: 0,
    height: "100%",
    maxHeight: "100%",
    overflow: "hidden",
  },
  /** Tighter stack under dashboard (team chat aligned with employee messages). */
  workspaceTeamDense: {
    gap: 1,
  },
  hubHeader: {
    borderRadius: "18px",
    border: "1px solid #E8EAED",
    bgcolor: "#fff",
    px: { xs: 1.5, sm: 2.5 },
    py: { xs: 1.5, sm: 2 },
    display: "flex",
    alignItems: { xs: "stretch", md: "center" },
    justifyContent: "space-between",
    gap: 2,
    flexWrap: "wrap",
    boxShadow: "0 8px 24px rgba(15, 23, 42, 0.04)",
  },
  /** Team channel hub card — matches dense `ChatModulePageFrame` header spacing. */
  hubHeaderTeamDense: {
    px: { xs: 1.5, sm: 1.75 },
    gap: 1.25,
    boxShadow: "0 2px 12px rgba(15, 23, 42, 0.04)",
  },
  hubTitleTeamDense: {
    fontSize: { xs: "1.125rem", sm: "1.3125rem" },
    fontWeight: 800,
    letterSpacing: "-0.02em",
    lineHeight: 1.2,
    color: "#0F172A",
  },
  teamTitleIconWrap: {
    flexShrink: 0,
    width: 36,
    height: 36,
    borderRadius: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#0D9488",
    bgcolor: "rgba(13, 148, 136, 0.1)",
    border: "1px solid rgba(13, 148, 136, 0.22)",
    boxShadow: "0 1px 2px rgba(15, 118, 110, 0.08)",
  },
  hubIntro: {
    flex: "1 1 220px",
    minWidth: 0,
  },
  hubTitle: {
    fontSize: { xs: "1.1rem", sm: "1.25rem" },
    fontWeight: 700,
    color: "#111827",
    lineHeight: 1.2,
  },
  hubSubtitle: {
    fontSize: "13px",
    color: "#6B7280",
    mt: 0.5,
    maxWidth: 560,
  },
  hubNavWrap: {
    flex: { xs: "1 1 100%", md: "0 1 auto" },
    display: "flex",
    justifyContent: { xs: "stretch", md: "flex-end" },
  },
  content: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 1.5,
    px: 2,
    py: 1.25,
    borderBottom: "1px solid #F3F4F6",
    bgcolor: "#FCFCFD",
    flexWrap: "wrap",
  },
} as const;
